[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
crossbeam = "0.8.2"
image = "0.24.7"
num = "0.4.1"
num_cpus = "1.16.0"
rayon = "1.8.0"
